require("lazy-config")
--require("nvim-tree-config")
--require("mason-config")
--require("mason-config.dap")
--require("lsp-config.nvim-cmp")
--require("lualine-config")
--require("treesitter-config")
--require("lsp-config.null-ls")
--require("notify-config")
-- require("autopairs-config")
require("mappings")
require("settings")
-- require('dap-python').setup('/usr/bin/python')
